# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
# define global settings here
# name: exampleapp # application name
# registry: exampleuser # dockerhub username or container registry hostname

# define multiple services here

services:
  - name: host
    project: src/Services/Api.Host/Api.Host.csproj
  - name: worker
    project: src/Services/Worker/Worker.csproj
  - name: mongo
    image: mongo
    bindings:
      - port: 29017
        connectionString: "mongo://${host}:${port}"
  - name: rabbit
    image: rabbitmq:3-management
    bindings:
      - port: 5672
        protocol: rabbitmq
