name:  Docker Host Build & Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build /src/Services/ --file /src/Services/Api.Host/Dockerfile --tag magic-media-host:$(date +%s) 
